[server]
port = 8501
address = "0.0.0.0"  # Allow external connections
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#4285f4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
